# This is a basic workflow to help you get started with Actions
#add env variable with version; is suffix is provided then take it, otherwise if dev branch then alpha-GITHUB_RUN_NUMBER suffix (1.14.0-alpha-20), if release then rc-GITHUB_RUN_NUMBER (1.14.0-rc-20)
name: Publish

# Controls when the workflow will run
on:
  workflow_dispatch:
    inputs:
      version-suffix:
        description: 'Version suffix (alpha-1, betta-2, preview-3, cr-4)'
        required: false

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  check_suffix:
    runs-on: ubuntu-latest
    outputs:
      run_other_jobs: ${{ steps.check-suffix.outputs.run_jobs }}
    steps:
      - name: check version suffix ${{ github.event.inputs.version-suffix }}
        id: check-suffix
        run: |
          if [[1 == 1 ]]; then
            echo "::set-output name=run_jobs::true"
          else
            echo "::set-output name=run_jobs::false"
          fi
            
  build:
    needs: [check_suffix]
    if: needs.check_suffix.outputs.run_other_jobs == 'true'
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:       
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: Version suffix
        run: echo Version suffix is ${{ github.event.inputs.version-suffix }}
        
      - name: Branch name
        run: echo running on branch ${GITHUB_REF##*/}

      # Runs a single command using the runners shell
      #- name: Run a one-line script
        #run: echo Hello, world!
