# This is a basic workflow to help you get started with Actions
#add env variable with version; is suffix is provided then take it, otherwise if dev branch then alpha-GITHUB_RUN_NUMBER suffix (1.14.0-alpha-20), if release then rc-GITHUB_RUN_NUMBER (1.14.0-rc-20)
name: publish-test

# Controls when the workflow will run
on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    if: ${{ startsWith(GITHUB_REF##*/, '[dev]||[release]') }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:       
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: Branch name
        run: echo running on branch ${GITHUB_REF##*/}

      # Runs a single command using the runners shell
      #- name: Run a one-line script
        #run: echo Hello, world!
