# This is a basic workflow to help you get started with Actions
#add env variable with version; is suffix is provided then take it, otherwise if dev branch then alpha-GITHUB_RUN_NUMBER suffix (1.14.0-alpha-20), if release then rc-GITHUB_RUN_NUMBER (1.14.0-rc-20)
name: Publish

# Controls when the workflow will run
on:
  workflow_dispatch:
    inputs:
      version-suffix:
        description: 'Version suffix (alpha-1, betta-2, preview-3, cr-4)'
        required: false

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  check_suffix:
    runs-on: ubuntu-latest
    outputs:
      match: ${{ steps.check-suffix.outputs.match }}
      suffix: ${{ steps.check-suffix.outputs.group1 }}
    steps:
      - uses: actions-ecosystem/action-regex-match@v2
        name: check version suffix ${{ github.event.inputs.version-suffix }}
        id: check-suffix
        with:
          text: ${{ github.event.inputs.version-suffix }}
          regex: '^(alpha|betta|preview|cr)-[0-9]+$'
          
      - name: Match
        run: echo Match is ${{ steps.check-suffix.outputs.match }}
        
      - name: Suffix
        run: echo Suffix is ${{ steps.check-suffix.outputs.suffix }}
            
  build:
    needs: [check_suffix]
    if: ${{ needs.check_suffix.outputs.match != '' }}
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: Version suffix
        run: echo Version suffix is ${{ github.event.inputs.version-suffix }}
        
      - name: Branch name
        run: echo running on branch ${GITHUB_REF##*/}

      # Runs a single command using the runners shell
      #- name: Run a one-line script
        #run: echo Hello, world!
